### ISSUE TITLE
[HEIF] Use of Layer Selector Property

### ISSUE THREAD

**Issue by cconcolato** [MPEGGroup/FileFormat#24]
The HEIF spec says:
> If the decoding of a multi-layer image item results into more than one reconstructed image, the 'lsel' item property shall be associated with the image item. ...

This has been discussed in the context of the AVIF specification, because AV1 images can be layered. We have a use case where the presence or absence of the LayerSelectorProperty would produce different results. If present, it would follow the HEIF specification. If not present and multiple reconstructed images are produced, the decoder is free to render them one by one, in a progressive decoding mode.

Can we change the 'shall' into 'should'? At least in the codec-agnostic part, keeping it a shall (if desired) for L-HEVC.

**Comment by jeanlf** [comment]
Yes we should say that ' lsel' is optional and if no lsel associated, item rendering is implementation specific and may be defined by derived specifications.

**Comment by kashyapks** [comment]
Making 'lsel' as an optional property and leaving the rendering to implementations will lead to interoperability issues. Implementations may choose to render the images in their own order and way which need not reflect the content providers intentions. 

Additionally, making 'lsel' property as optional will impact legacy implementations, as this is mandatory now.

**Comment by cconcolato** [comment]
Thanks @kashyapks. 
Regarding legacy implementations, the proposal is to keep it mandatory for codecs that relied on it (e.g. L-HEVC) but to leave the choice for new codecs.
The current specification mandates the presence of the box as soon as the coded image is layered, but it does not mandate any behavior for the client, so I think the interoperability issue is the same. Actually, I think it's even better with the proposed approach: because you know that when `lsel` is present, it is an explicit indication to the renderer to only render this layer. The current specification has no way to tell the renderer: do progressive rendering.

**Comment by kashyapks** [comment]
Decoding of a coded image item results into exactly one reconstructed image, since otherwise it might not be possible to apply subsequent transformative properties unambiguously or use the coded image item as a source for a derived image item unambiguously. 

For example, if a scaling transformative property is used, it needs to be unambiguous what is the width and height of the reconstructed image. Thus, if the decoding of a multi-layer image item results into more than one reconstructed image, the 'lsel' item property shall be associated with the image item to make it clear which decoded output image is considered as the reconstructed image for further transformations and derivations. 

An example of when 'lsel' was intended to be used is a stereoscopic image, whereas 'lsel' was not envisioned to be needed for spatial or quality scalability.

Perhaps the requirement of the 'lsel' presence could be clarified with highlighted text proposed to be added as below:

If the decoding of a multi-layer image item results into more than one reconstructed image `that is output by the decoding process`, the 'lsel' item property shall be associated with the image item.

A NOTE could be also added as follows:
NOTE: If a multi-layer image item contains spatial or quality enhancement layers and is to be displayed, players could choose to decode and display the layers progressively.

**Comment by dwsinger** [comment]
Perhaps the layer that is identified by the property is (a) what you would print, if you're printing ("the" image) and/or (b) the 'final' image if you're on screen? That is, maybe there's an indication that in this use, the author only wants/needs the intermediate resolution as the 'final' output. A renderer would be free to display lower resolutions on the way, of course – or, if it has a super-high-pixel-density-screen and time to spare, display a higher resolution?

**Comment by cconcolato** [comment]
> Decoding of a coded image item results into exactly one reconstructed image, since otherwise it might not be possible to apply subsequent transformative properties unambiguously or use the coded image item as a source for a derived image item unambiguously.

why? a renderer could apply the transformations each time a new reconstructed image is produced? I need to check, but I'm not sure transformations declare what properties the input image has, it only describes the output.

> An example of when 'lsel' was intended to be used is a stereoscopic image, whereas 'lsel' was not envisioned to be needed for spatial or quality scalability.

The problem is exactly that. `lsel` is mandatory for layered images, even for spatial or quality scalability. The proposal is to relax that rule for new codecs. I don't understand how your proposed change fixes the problem.

**Comment by cconcolato** [comment]
@dwsinger one thing to clarify is the interaction between `lsel` and `ispe`. In a layered image with layer resolution changes, which dimensions are documented by `ispe`? One interpretation is that `ispe` reflects the layer mentioned in `lsel`. Another is that `lsel` has no impact and documents the highest dimensions.

**Comment by dwsinger** [comment]
the lsel says it identifies the layer that ispe and other properties document…

**Comment by leo-barnes** [comment]
> Decoding of a coded image item results into exactly one reconstructed image, since otherwise it might not be possible to apply subsequent transformative properties unambiguously or use the coded image item as a source for a derived image item unambiguously.
> 
> For example, if a scaling transformative property is used, it needs to be unambiguous what is the width and height of the reconstructed image. Thus, if the decoding of a multi-layer image item results into more than one reconstructed image, the 'lsel' item property shall be associated with the image item to make it clear which decoded output image is considered as the reconstructed image for further transformations and derivations.
> 
> An example of when 'lsel' was intended to be used is a stereoscopic image, whereas 'lsel' was not envisioned to be needed for spatial or quality scalability.
> 
> Perhaps the requirement of the 'lsel' presence could be clarified with highlighted text proposed to be added as below:
> 
> If the decoding of a multi-layer image item results into more than one reconstructed image `that is output by the decoding process`, the 'lsel' item property shall be associated with the image item.
> 
> A NOTE could be also added as follows: NOTE: If a multi-layer image item contains spatial or quality enhancement layers and is to be displayed, players could choose to decode and display the layers progressively.

I don't really agree with this. I feel like this restricts some valid use-cases for no clear reason. I would much prefer the behaviour that @cconcolato  is proposing since it is otherwise more or less impossible to use multi-layering for progressive rendering (which I would actually say is the more realistic use-case).

The way I see it working is:
1. If `lsel` is present, the writer wants you to decode and show **only** the specified layer.
2. If `lsel` is absent but there are multiple layers, the final layer is the one that should be shown (and also the one that `ispe` and all transformative properties apply to).
3. If `lsel` is absent and there are multiple layers, the renderer **may** chose to display the intermediate layers in order to achieve progressive refinement. The renderer will need to handle cases where the intermediate layers do not have the same dimensions as the final layer.

What is missing is a stronger clarification that when the renderer chooses to display intermediate layers it also needs to apply any transformative properties, but that seems like it should be the obvious behaviour.

If the renderer does not want to do progressive refinement, the absence of `lsel` does not really make any difference as long as it's clear to everyone which the default layer is.

**Comment by cconcolato** [comment]
@leo-barnes can we close this issue from the MPEG side or do you think MPEG needs to do something?

**Comment by leo-barnes** [comment]
I think it can be closed.
