### ISSUE TITLE
ISOBMFF Sample durations and Track fragment decode time (tfdt)

### ISSUE THREAD

**Issue by dwsinger** [MPEGGroup/FileFormat#3]
It's unclear what the defined behavior is (if any) if the tfdt value is less than the computed sum of previous durations. What is the player supposed to do? Perhaps we could truncate a previous duration, but what if whole samples are elided?
Should we allow an 'indefinite' value (perhaps 0) for the last sample in a track fragment, and it's resolved by inspecting the tfdt of the next fragment (when it's available)? Is this any better than assigning an arbitrary short value and extending (as currently permitted) or some sort of truncation of an arbitrary long value (as suggested above)?

There is extensive suggested editing in the Defect Report. Are we ready to go?

**Comment by waqarz** [comment]
[w18812](http://wg11.sc29.org/doc_end_user/documents/128_Geneva/wg11/w18812.zip) Revised Defect report for ISO/IEC 14496-12 outlines a solution. The discussion on defect report in [m47254](http://wg11.sc29.org/doc_end_user/documents/126_Geneva/wg11/m47254-v1-m47254.zip) at 126th MPEG resolved to: We could add a formal definition of sample duration, to start on 3.6. 

There were a few other concerns documented in m47254, namely:

1. Decoders perceiving two sample at the same decoding time
2. calculations of bit-rate or frame-rate result in divide-by-zero
3. Probably due to above software crashes

These are backward compatibility considerations for a legacy client. If a legacy decoder exhibits any one of the above 3 behaviours, it will not be able to present the targeted sparse track anyway, so the fact that they will stumble decoding such tracks is already known. A zero decoding time signalling would be done in ecosystems to support sparse tracks and with an assurance that the decoders are capable of handling such tracks.

**Comment by jeanlf** [comment]
I'm not sure I follow the question here. 
- If the tfdt is less than the sum this is an error of the file, as per spec.
- if the tfdt is more the the sum and the last received sample has a non-0 duration this is an error in the file
- otherwise file is OK

Do we need to clarify how readers should process non-compliant files ?
O r de we want to relax tfdt ??

**Comment by dwsinger** [comment]
The editorial update in the 7th applies Waqar's changes; close?

**Comment by jeanlf** [comment]
Yes I think we can close. Maybe for the sake of clarity in 8.8.12.1 we could add after "If no samples were present in the preceding movie and movie fragments...":

"Otherwise, the time expressed in the TrackFragmentBaseMediaDecodeTimeBox shall not be less than the the sum of the sample durations of the samples in the preceding movie and movie fragments."

**Comment by dwsinger** [comment]
The requirement to not be less than the previous sum, is in the amendment going to CD. are there other aspects, or can this be closed?

**Comment by cconcolato** [comment]
So the CD covers 1)? I'll check. We should still address 2) and 3) I think.

**Comment by cconcolato** [comment]
Here is the status in the Revised Text of the 2nd DIS of the 8th edition (MDS23485_WG03_N01118), the semantics of `basedMediaDecodeTime` are still:
> `baseMediaDecodeTime` is an integer equal to the sum of the decode durations of all earlier samples in the media, expressed in the media's timescale. It does not include the samples added in the enclosing track fragment.

So I still think we should update the semantics to be:
> `baseMediaDecodeTime` is the absolute decoding timestamp, measured on the decoding timeline, of the first sample in decoding order in the track fragment, expressed in the media's timescale. It shall not be smaller than the sum of the decode durations of all earlier samples in the media.

And the comments 2 and 3 in https://github.com/MPEGGroup/FileFormat/issues/3#issuecomment-948067856 have not been addressed either.

**Comment by mhannuksela** [comment]
I agree on the proposed semantics change in principle, although the second sentence needs some wordsmithing IMO. Here is a try:

> `baseMediaDecodeTime` is the absolute decoding timestamp, measured on the decoding timeline, of the first sample in decoding order in the track fragment, expressed in the media's timescale. The value of `baseMediaDecodeTime` shall be greater than or equal to the sum of the sample durations of all the samples of this track that precede this track fragment in decoding order.

**Comment by cconcolato** [comment]
We add it to AMD2 of 8th edition.
