### ISSUE TITLE
undefined earliest presentation time in sidx box

### ISSUE THREAD

**Issue by RufaelDev** [MPEGGroup/FileFormat#30]
In some cases segments may exist that are edited out of a presentation, in this case the SegmentIndexBox earliest presentation time is undefined, it may be good to add some text to deal with this case. This may be a limitation in some cases such as when using an edit list https://github.com/MPEGGroup/CMAF/issues/27

It would be good to define what the earliest presentation time should be in such a case.

**Comment by jeanlf** [comment]
I'm not sure I understand the issue here, let me try to recap

#Case 1: VoD, 1 sidx for the entire pres
The earliest presentation time is known
- if a sub segment is completely edited out, I would expect a subsegment_duration of 0. If next segment is SAP1/2, I can safely discard this segment. Otherwise I need to process it.
- otherwise, a subsegment_duration equal to what is presented from the segment  

#Case 2: live,  1 sidx per segment
- if the given segment is completely edited out, the earliest presentation time is unknown, but that segment should not be present at all (at least when all your segments start with SAP1/2)
- otherwise, earliest presentation time is known

So the only problem I see if for the case of live where you edit out a segment in the middle but still need to send it due to coding dependencies (next segment will not start with SAP1/2). 

Is that a good recap ?

**Comment by jeanlf** [comment]
@cconcolato regarding your  example 1:
- if you don't list the repeated moof1, it's likely that a player will consider the presentation over (there is a mismatch between presentation duration of edit list and sidx)
- if you list the repeated moof1 with size 0, a player tuning at moof2 won't be able to play properly

I thought of dealing with this is by using hierarchical sidx, where the entry for the repeated moof1 is `reference_type=1` and the associated sidx (sidx_r1) would give the size and duration of moof1, but that doesn't work either because the sidx_r1 first_offset must point to something after the sidx_r1 box, which is not the case.

We miss something in sidx if we want to deal with complex edit lists with content repeat...

**Comment by dwsinger** [comment]
do we need an 'undefined' value for earliest presentation time as well as duration?

**Comment by cconcolato** [comment]
This issue is being investigated in the context of CMAF (GitLab).
