### ISSUE TITLE
Editor link for 23001-10 2nd is wrong

### ISSUE THREAD

**Issue by timse7** [MPEGGroup/FileFormat#65]
It points to ISO/IEC 23001-7:2016. Please update. Thank you.

**Comment by podborski** [comment]
I believe I also fixed it in the CSV branch?

**Comment by cconcolato** [comment]
I did

**Comment by podborski** [comment]
Great, there was another link I changed and I was not sure if this issue was related. But it was another thing, It was for CICP spec. 

Changed:

[Published \[](https://sd.iso.org/projects/project/57794/overview)[editor link](https://sd.iso.org/projects/project/57794/overview)\]

to

[Published](https://www.iso.org/standard/57794.html)<br>[editor-link](https://sd.iso.org/projects/project/57794/overview)
